Fixed bug that `config-center` conflicts with `metrics`. (#3769)
TypeError: Hyperf\ConfigCenter\AbstractDriver::onPipeMessage(): Argument #1 ($pipeMessage) must be of type Hyperf\ConfigCenter\Contract\PipeMessageInterface, Hyperf\Metric\Adapter\RemoteProxy\Histogram given